project_id = "rmofmkjmzwkxjzfirbpt"

[functions.map-tile-proxy]
verify_jwt = false

[functions.cast-vote]
verify_jwt = false

[functions.analyze-cam-protocol]
verify_jwt = false

[functions.analyze-dat-spr]
verify_jwt = false
