project_id = "adagjmvhlmghhmadtpwv"

[functions.tibia-relic-proxy]
verify_jwt = false

[functions.save-highscores]
verify_jwt = false

[functions.get-top-gainers]
verify_jwt = false

[functions.scrape-item-details]
verify_jwt = false

[functions.scrape-rune-details]
verify_jwt = false

[functions.track-online-players]
verify_jwt = false

[functions.analyze-alt-matches]
verify_jwt = false
