name: Build and Package Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build:fast

    - name: Upload dist folder (GitHub zipa automaticamente)
      uses: actions/upload-artifact@v4
      with:
        name: project-dist
        path: dist
        retention-days: 2

    - name: Upload source code
      uses: actions/upload-artifact@v4
      with:
        name: project-source
        path: |
          src/
          public/
          index.html
          package.json
          package-lock.json
          vite.config.ts
          tailwind.config.ts
          tsconfig.json
          tsconfig.app.json
          tsconfig.node.json
          components.json
          postcss.config.js
          eslint.config.js
          README.md
        retention-days: 2
